# Site settings
title: Athens Women in Tech
email: comm@athenswomenintech.com
description: We are a new group, operating under Software Developers of Athens. We are dedicated to connecting women in the tech community of Athens, Ga.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.athenswomenintech.com" # the base hostname & protocol for your site
twitter_username: AthensWIT
github_username:  AthensWIT

# Build settings
markdown: kramdown
