# Site settings
title: Athens Women in Tech
email: comm@athenswomenintech.com
url: https://AthensWIT.github.io
description: "We're a community of developers, designers, computer fans, and
aspiring technologists in Athens, Georgia. Our focus is on creating a
collaborative support group for any and all women in Athens who'd like to
continue learning more about using technology more effectively (and isn't that
all of us)?"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 6d6867 #80B3FF
  secondary: b8b3b1 #FD6E8A
  secondary-dark: db4b64 # Awesome blue 6A7991

# Footer settings
footer:
  copyright: Athens Women in Tech
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/athenswit
  - title: facebook
    url: http://facebook.com/AthensWIT
  - title: github
    url: http://github.com/AthensWIT

# Postal address (add as many lines as necessary)
address:
  - line: 345 W Hancock Ave
  - line: Suite 202
  - line: Athens, GA 30601

# Credits content
credits: 'Thanks to <a href="http://lizshinndesign.com">Liz Shinn</a> for the logo and brand design.'

# Build settings
markdown: kramdown
permalink: pretty

collections:
  events:
    output: true
    permalink: /events/:path/
